/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileProfileIdRouteRouteImport } from './routes/profile.$profileId/route'
import { Route as ProfileProfileIdIndexRouteImport } from './routes/profile.$profileId/index'
import { Route as ProfileProfileIdOverviewRouteImport } from './routes/profile.$profileId/overview'
import { Route as ProfileProfileIdInsightsRouteImport } from './routes/profile.$profileId/insights'
import { Route as ProfileProfileIdAgentsRouteImport } from './routes/profile.$profileId/agents'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileProfileIdRouteRoute = ProfileProfileIdRouteRouteImport.update({
  id: '/profile/$profileId',
  path: '/profile/$profileId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileProfileIdIndexRoute = ProfileProfileIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileProfileIdRouteRoute,
} as any)
const ProfileProfileIdOverviewRoute =
  ProfileProfileIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => ProfileProfileIdRouteRoute,
  } as any)
const ProfileProfileIdInsightsRoute =
  ProfileProfileIdInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => ProfileProfileIdRouteRoute,
  } as any)
const ProfileProfileIdAgentsRoute = ProfileProfileIdAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => ProfileProfileIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile/$profileId': typeof ProfileProfileIdRouteRouteWithChildren
  '/profile/$profileId/agents': typeof ProfileProfileIdAgentsRoute
  '/profile/$profileId/insights': typeof ProfileProfileIdInsightsRoute
  '/profile/$profileId/overview': typeof ProfileProfileIdOverviewRoute
  '/profile/$profileId/': typeof ProfileProfileIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile/$profileId/agents': typeof ProfileProfileIdAgentsRoute
  '/profile/$profileId/insights': typeof ProfileProfileIdInsightsRoute
  '/profile/$profileId/overview': typeof ProfileProfileIdOverviewRoute
  '/profile/$profileId': typeof ProfileProfileIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile/$profileId': typeof ProfileProfileIdRouteRouteWithChildren
  '/profile/$profileId/agents': typeof ProfileProfileIdAgentsRoute
  '/profile/$profileId/insights': typeof ProfileProfileIdInsightsRoute
  '/profile/$profileId/overview': typeof ProfileProfileIdOverviewRoute
  '/profile/$profileId/': typeof ProfileProfileIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile/$profileId'
    | '/profile/$profileId/agents'
    | '/profile/$profileId/insights'
    | '/profile/$profileId/overview'
    | '/profile/$profileId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile/$profileId/agents'
    | '/profile/$profileId/insights'
    | '/profile/$profileId/overview'
    | '/profile/$profileId'
  id:
    | '__root__'
    | '/'
    | '/profile/$profileId'
    | '/profile/$profileId/agents'
    | '/profile/$profileId/insights'
    | '/profile/$profileId/overview'
    | '/profile/$profileId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileProfileIdRouteRoute: typeof ProfileProfileIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$profileId': {
      id: '/profile/$profileId'
      path: '/profile/$profileId'
      fullPath: '/profile/$profileId'
      preLoaderRoute: typeof ProfileProfileIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$profileId/': {
      id: '/profile/$profileId/'
      path: '/'
      fullPath: '/profile/$profileId/'
      preLoaderRoute: typeof ProfileProfileIdIndexRouteImport
      parentRoute: typeof ProfileProfileIdRouteRoute
    }
    '/profile/$profileId/overview': {
      id: '/profile/$profileId/overview'
      path: '/overview'
      fullPath: '/profile/$profileId/overview'
      preLoaderRoute: typeof ProfileProfileIdOverviewRouteImport
      parentRoute: typeof ProfileProfileIdRouteRoute
    }
    '/profile/$profileId/insights': {
      id: '/profile/$profileId/insights'
      path: '/insights'
      fullPath: '/profile/$profileId/insights'
      preLoaderRoute: typeof ProfileProfileIdInsightsRouteImport
      parentRoute: typeof ProfileProfileIdRouteRoute
    }
    '/profile/$profileId/agents': {
      id: '/profile/$profileId/agents'
      path: '/agents'
      fullPath: '/profile/$profileId/agents'
      preLoaderRoute: typeof ProfileProfileIdAgentsRouteImport
      parentRoute: typeof ProfileProfileIdRouteRoute
    }
  }
}

interface ProfileProfileIdRouteRouteChildren {
  ProfileProfileIdAgentsRoute: typeof ProfileProfileIdAgentsRoute
  ProfileProfileIdInsightsRoute: typeof ProfileProfileIdInsightsRoute
  ProfileProfileIdOverviewRoute: typeof ProfileProfileIdOverviewRoute
  ProfileProfileIdIndexRoute: typeof ProfileProfileIdIndexRoute
}

const ProfileProfileIdRouteRouteChildren: ProfileProfileIdRouteRouteChildren = {
  ProfileProfileIdAgentsRoute: ProfileProfileIdAgentsRoute,
  ProfileProfileIdInsightsRoute: ProfileProfileIdInsightsRoute,
  ProfileProfileIdOverviewRoute: ProfileProfileIdOverviewRoute,
  ProfileProfileIdIndexRoute: ProfileProfileIdIndexRoute,
}

const ProfileProfileIdRouteRouteWithChildren =
  ProfileProfileIdRouteRoute._addFileChildren(
    ProfileProfileIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileProfileIdRouteRoute: ProfileProfileIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
